[package]
name = "state_estimation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.4"

[lib]
name = "state_estimation"
crate-type = ["cdylib"]
